AdminLTE1/Models/Service.cs
namespace AdminLTE1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("gsDatabase.Service")]
    public partial class Service
    {
        [Key]
        public int ItemID { get; set; }

        [Required]
        [StringLength(45)]
        public string ItemName { get; set; }

        [Required]
        [StringLength(45)]
        public string CapacityType { get; set; }

        public int Capacity { get; set; }

    
        [StringLength(45)]
        public string Photo { get; set; }

        [Required]
        [StringLength(245)]
        public string Specification { get; set; }

        [StringLength(45)]
        public string OtherCharges { get; set; }

        [StringLength(45)]
        public string Other1 { get; set; }

        [StringLength(45)]
        public string Other2 { get; set; }

        [StringLength(45)]
        public string Other3 { get; set; }

        public int OverrideRateID { get; set; }

        public int FixedRateID { get; set; }
    }
}

AdminLTE1/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminLTE1.Models;
using System.IO;
using PagedList;

namespace AdminLTE1.Controllers
{
    public class ServicesController : Controller
    {
        private GSMYSQL db = new GSMYSQL();

        // GET: Services
        public ActionResult Index(int? pageNumber)
        {

            return View(db.Services.ToList());

        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ItemID,ItemName,CapacityType,Capacity,Photo,Specification,OtherCharges,Other1,Other2,Other3,OverrideRateID,FixedRateID")] Service service)
        public ActionResult Create (Service service , HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                //db.Services.Add(service);
                //db.SaveChanges();
                //return RedirectToAction("Index");

                string path = Path.Combine(Server.MapPath("/zxcimg42asfd"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                db.Services.Add(new Service
                {
                    ItemID = service.ItemID,
                    ItemName = service.ItemName,
                    Capacity = service.Capacity,
                    CapacityType = service.CapacityType,
                    Photo = "/zxcimg42asfd/" + file.FileName,
                    Specification = service.Specification,
                    OtherCharges = service.OtherCharges,
                    OverrideRateID = service.OverrideRateID,
                    FixedRateID = service.FixedRateID,
                });
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(service);
        }

        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Service service,HttpPostedFileBase file, int id)
        {
            if (ModelState.IsValid)
            {
              Service s = db.Services.Find(id);
                string path = Path.Combine(Server.MapPath("~/zxcimg42asfd"), Path.GetFileName(file.FileName));
                file.SaveAs(path);

                s.ItemID = service.ItemID;
                s.ItemName = service.ItemName;
                s.Capacity = service.Capacity;
                s.CapacityType = service.CapacityType;
                s.Photo = "~/zxcimg42asfd/" + file.FileName;
                s.Specification = service.Specification;
                s.OtherCharges = service.OtherCharges;
                s.OverrideRateID = service.OverrideRateID;
                s.FixedRateID = service.FixedRateID;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminLTE1/Views/Services/Create.cshtml
@model AdminLTE1.Models.Service

@{
    ViewBag.Title = "Create Services";
}


@using (Html.BeginForm("Create", "Services", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CapacityType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CapacityType", new List<SelectListItem>
           {
                     new SelectListItem{ Text="Select Room Type", Value = "0" },
               new SelectListItem{ Text="Room", Value = "Room" },
               new SelectListItem{ Text="Function Hall", Value = "Function Hall" }
             })
                @*@Html.EditorFor(model => model.CapacityType, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.CapacityType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" /><br /><br />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Specification, 10, 147, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherCharges, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherCharges, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherCharges, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverrideRateID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OverrideRateID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OverrideRateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FixedRateID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FixedRateID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FixedRateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdminLTE1/Views/Services/Delete.cshtml
@model AdminLTE1.Models.Service

@{
    ViewBag.Title = "Delete Services";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CapacityType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CapacityType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherCharges)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherCharges)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Other1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Other1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Other2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Other2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Other3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Other3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OverrideRateID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OverrideRateID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixedRateID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixedRateID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdminLTE1/Views/Services/Details.cshtml
@model AdminLTE1.Models.Service

@{
    ViewBag.Title = "Service Details";
}



<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CapacityType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CapacityType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherCharges)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherCharges)
        </dd>

       
        <dt>
            @Html.DisplayNameFor(model => model.OverrideRateID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OverrideRateID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixedRateID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixedRateID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdminLTE1/Views/Services/Edit.cshtml
@model AdminLTE1.Models.Service

@{
    ViewBag.Title = "Edit Services";
}




@using (Html.BeginForm("Edit", "Services", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CapacityType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CapacityType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CapacityType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.Photo)" alt="Image" height="50" width="50" />
                <input type="file" name="file" id="file" /><br /><br />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherCharges, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherCharges, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherCharges, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverrideRateID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OverrideRateID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OverrideRateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FixedRateID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FixedRateID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FixedRateID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdminLTE1/Views/Services/Index.cshtml
@model IEnumerable<AdminLTE1.Models.Service>

@{
    ViewBag.Title = "Services Overview";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CapacityType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Specification)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherCharges)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.OverrideRateID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FixedRateID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CapacityType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacity)
        </td>
        <td>
            <img src="@Url.Content(item.Photo)" alt="Image" height="50" width="50" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Specification)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OtherCharges)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OverrideRateID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FixedRateID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ItemID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ItemID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ItemID })
        </td>
    </tr>
}

</table>